### ISSUE TITLE
Benchmark for 0.3.0 release.

### ISSUE THREAD

**Issue by yueawang** [Intel-bigdata/OAP#376]
## Benchmark Framework:
Consider HiBench

## Benchmark Testcases:
Queries in production environment.

## Benchmark configuration:
Format\Version| 0.2.0 baseline | 0.3.0 target
------------|------------ | -------------
oap | Profile 1| Profile 2 |
parquet | N/A | Profile 3 |

## Ideal Benchmark Results
General: profile 1 <= profile 2 ~= profile 3
Special: profile 1 << profile 2  ~= profile 3

**Comment by yueawang** [comment]
Add more test profile.

Format\Version | 0.2.0 baseline | 0.3.0 target
-- | -- | --
oap | Profile 1 | Profile 2
oap w/ index | Profile 3 | Profile 4
parquet | N/A | Profile 5
parquet w/ index | N/A | Profile 6

Ideal result is : (profile 6 ~= profile 4) > (profile 3) >> (profile 2 ~= prifile 1 ~= profile 5)
I.E. 0.3.0's index improves the query more than 0.2.0 does, and oap format at least has same perf as parquet (if not better in some cases.).

**Comment by xuyangit** [comment]
Currently we focus on testing of B-tree and Bitmap. The detailed information of the table is listed as follows:

| Table       | Num of rows | Num of columns |
| ----------- | ----------- | -------------- |
| store_sales | 86398328    | 23             |

**Table1. Information of tables** 

The sizes of original table and exported table on single attribute for indexing are as follows:

| Data format | Original file size | File size on ss_ticket_number | File size on ss_item_sk |
| ----------- | ------------------ | ----------------------------- | ----------------------- |
| oap         | **3.5GB**          | **14MB**                      | 188MB                   |
| parquet     | 4.0GB              | 52.3MB                        | **158MB**               |

**Table2. Data size of table store_sales (same for 0.2 and 0.3)**

We select the **ss_ticket_number** (7M different values) of **store_sales** table to build the B-Tree index, **ss_item_sk** (40K different values) of **store_sales** table to build the Bitmap index and **c_email_address** of **customer** table to build the Trie index. The detailed index cost is as follows:

| Version | Build time | Size  | Drop time |
| ------- | ---------- | ----- | --------- |
| OAP-0.2 | 9530ms     | 1.0GB | 913ms     |
| OAP-0.3 | 4903ms     | 412MB | 881ms     |

**Table3. Cost for B-Tree (same for oap and parquet format)**

| Version | Build time | Size  | Drop time |
| ------- | ---------- | ----- | --------- |
| OAP-0.2 |            |       |           |
| OAP-0.3 | 6010ms     | 499MB | 891ms     |

**Table4. Cost for Bitmap** (OAP-0.2 fails to build bitmap index due to not enough heap space)

**Query Performance**
For tests for each index, we generate queries covering 1 to 3 columns. The sizes of retrieved results generally covers frequent cases. Besides, each query is measured 3 times to get the average time. Before each test, we have flushed and cleared the cache using related Linux commands. 

| Version                     | Q1       | Q2   | Q3   | Q4   | Q5      | Q6      | Q7      | Q8   | Q9   | Q10  | Q11  | Q12  | Q13  | Q14  |
| --------------------------- | -------- | ---- | ---- | ---- | ------- | ------- | ------- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| OAP-0.2(oap format) | 2435 | 1972 | 2286 | 907 | 1020 | 552 | 1260 | 2403 | 1737 | 1778 | 1622 | 2173 | 2136 | 1568 |
| OAP-0.2(parquet format) | 2921 | 2555 | 2260 | 591 | 864 | 841 | 1209 | 2682 | 2476 | 1852 | 1982 | 2144 | 2334 | 1901 |
| OAP-0.3(oap format)         | **2056** | 1386 | 1178 | 519  | **470** | **427** | **378** | 1267 | 1454 | 1245 | 1288 | 1467 | 1480 | 1213 |
| OAP-0.3(parquet format)     | 2781     | 1269 | 1111 | 518  | 528     | 504     | 463     | 1454 | 1295 | 1269 | 1174 | 1369 | 2239 | 1316 |
| Spark-2.1.0(oap format)     | 6708     | 882  | 750  | 693  | 675     | 688     | 554     | 771  | 924  | 705  | 724  | 823  | 935  | 820  |
| Spark-2.1.0(parquet format) | 6827     | 916  | 807  | 632  | 686     | 490     | 538     | 720  | 766  | 688  | 533  | 590  | 614  | 482  |

**Table5. Result for B-Tree index (Average time)**

| Version                     | Q1       | Q2   | Q3   | Q4   | Q5      | Q6      | Q7      | Q8   | Q9   | Q10  | Q11  | Q12  | Q13  | Q14  |
| --------------------------- | -------- | ---- | ---- | ---- | ------- | ------- | ------- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| OAP-0.2(oap format) | 2428 | 1692 | 1808 | 1027 | 1212 | 505 | 1452 | 2294 | 1592 | 1672 | 1494 | 1797 | 2087 | 1383 |
| OAP-0.2(parquet format) | 2835 | 2177 | 1467 | 554 | 782 | 1383 | 1393 | 2258 | 1854 | 1754 | 1812 | 2069 | 2215 | 1836 |
| OAP-0.3(oap format) | 1967 | 1234 | 1081 | 416 | 449 | 368 | 314 | 1217 | 1330 | 1228 | 1194 | 1410 | 1320 | 1099 |
| OAP-0.3(parquet format) | 2413 | 1199 | 1091 | 453 | 511 | 404 | 430 | 1293 | 1235 | 1185 | 1090 | 1275 | 1340 | 1284 |
| Spark-2.1.0(oap format) | 6412 | 833 | 619 | 675 | 659 | 600 | 473 | 705 | 889 | 642 | 685 | 777 | 1021 | 763 |
| Spark-2.1.0(parquet format) | 6697 | 1125 | 716 | 602 | 444 | 446 | 485 | 630 | 1061 | 638 | 489 | 526 | 542 | 439 |

**Table6. Result for B-Tree index (Best time)**

| Version              | Q1    | Q2    | Q3   | Q4   | Q5    | Q6    | Q7   | Q8   | Q9    | Q10   | Q11  |
| -------------------- | ----- | ----- | ---- | ---- | ----- | ----- | ---- | ---- | ----- | ----- | ---- |
| OAP-0.3(oap format) | 68682 | 19524 | 652 | 601 | 72263 | 18477 | 997 | 934 | 68996 | 18440 | 965 |
| OAP-0.3(parquet format) | 5049 | 1043 | 753 | 741 | 3633 | 1167 | 860 | 771 | 4518 | 1184 | 815 |
| Spark-2.1.0(oap format) | 3951 | 914 | 528 | 572 | 3378 | 1109 | 749 | 718 | 4163 | 1233 | 833 |
| Spark-2.1.0(parquet format) | 4274 | 874 | 457 | 477 | 3678 | 866 | 783 | 554 | 4265 | 1275 | 619 |

**Table7. Result for Bitmap index-average time (OAP-0.2 fails to build index due to not enough heap space)**

| Version              | Q1    | Q2    | Q3   | Q4   | Q5    | Q6    | Q7   | Q8   | Q9    | Q10   | Q11  |
| -------------------- | ----- | ----- | ---- | ---- | ----- | ----- | ---- | ---- | ----- | ----- | ---- |
| OAP-0.3(oap format) | 1967 | 1234 | 1081 | 416 | 449 | 368 | 314 | 1217 | 1330 | 1228 | 1194 |
| OAP-0.3(parquet format) | 2413 | 1199 | 1091 | 453 | 511 | 404 | 430 | 1293 | 1235 | 1185 | 1090 |
| Spark-2.1.0(oap format) | 6412 | 833 | 619 | 675 | 659 | 600 | 473 | 705 | 889 | 642 | 685 |
| Spark-2.1.0(parquet format) | 6697 | 1125 | 716 | 602 | 444 | 446 | 485 | 630 | 1061 | 638 | 489 |


**Table8. Result for Bitmap index-best time (OAP-0.2 fails to build index due to not enough heap space)**

**Comment by xuyangit** [comment]
We'll move to bigger data today. More results will be published next day.

**Comment by linhong-intel** [comment]
@xuyangit Thanks very much.
One question:
Table 6, Row 1, some query time are 10+ times slower than others. Is this correct?

**Comment by lee-lei** [comment]
Thanks so much for the detailed data. I have some questions below.
1. Would you please add the specific information about oap 0.3(e.g. until which commit on the master)you are using to get the data?
2. For Q3, Q8 and Q11 in Table8 and Table7, it seems that the best is worse than the average for oap bitmap index.

**Comment by xuyangit** [comment]
@lee-lei There may some problems with statistic yesterday. New data is published and the average case is discarded due to some weird time cases. All original data is published and bigger table(around 3G rows are used) is used for test now. The result for tpcds 1000 scale may be more convincing. 
I will add information of specific version later, tks!
