### ISSUE TITLE
Too much deviation in Guava Cache‘ Weigher.

### ISSUE THREAD

**Issue by songzhan01** [Intel-bigdata/OAP#528]
MB is used to weigh cache entries at present. But, there are many FiberCache which size is less than MB since partial loading was supported.  In my test environment，Cache eviction was performed when practical used off-heap  was about 100M although off-heap is set 600MB in
Executor.

For example:
cacheMemory=600MB,  MAX_WEIGHT=600(600MB/MB)
each FiberCache‘ size = 100KB
weight=math.ceil(FiberCache.size() / MB)=1
practical used memory = 60MB.

So, KB or B may be a better choice for Guava Cache‘ Weigher.
@linhong-intel

**Comment by linhong-intel** [comment]
Thanks @songzhan01 
This is a good finding.
Let's discuss more about this on Thursday.
My short answer is:
Change to KB is OK. Change to B will cause an overflow problem due to Guava internal bug.
Rather than this, I prefer to find a way to make sure all fibers are larger than, say, 16MB.

**Comment by chenghao-intel** [comment]
Yes, I also agree KB is a more proper granularity than MB.

**Comment by songzhan01** [comment]
Ok.

**Comment by carsonwang** [comment]
I saw guava's `maximumWeight` is a long instead of int. How could the overflow problem happen, @linhong-intel ?

**Comment by linhong-intel** [comment]
@carsonwang 
https://github.com/google/guava/commit/adcd9984bb9a93db4ab94ceba0583520745e2b01

There are 2 `weight` in LocalCache
`maxWeight` in Line 190 is long
`totalWeight` in Line 2081 is int
`totalWeight` is the indicator for eviction.
for example:
`totalWeight = Int.MAX - 1`
then add one cache with weight 10.
`totalWeight += 10 // totalWeight = -9 since overflow`
then `totalWeight < maxWeight / concurrencyLevel`

**Comment by linhong-intel** [comment]
fixed by #532. Let's use another issue to track small fiber issue.
