### ISSUE TITLE
OapFileFormat Support FileSplit

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#537]
Now OapFileFormat not support FileSplit，and in our performance testing we found parquet use ParquetFileFormat with oap-enable is slow 15% than use ParquetFileFormat with oap-disable because oap-enable will force disable "isSplitable" func value，and there will be more network io when a file has multiple dfs-blocks，in the following google-doc is my idea of optimization 

https://docs.google.com/document/d/1uG82OTwPUmRYmzZgrgpCGxddw7GD-Xjkid4rWywsaN0/edit?usp=sharing

**Comment by linhong-intel** [comment]
1 idea:
Let's use option#1 and use a virtual key called (row_group_id) during build index.
For example: "create oindex on table_1 (column_A)". Then we use (row_group_id, column_A) as index key.

Then every task will only load the needed index data for reading row group, maybe this will save memory. Also, since current index file size is relatively small, add a virtual key should be acceptable.

**Comment by LuciferYang** [comment]
close this, no more related work.
