### ISSUE TITLE
Index file is not completed randomly

### ISSUE THREAD

**Issue by linhong-intel** [Intel-bigdata/OAP#636]
Some findings for now:
1. speculation seems the most possible reason. (Not seen so far without speculation)
2. Index Record Writer closed and flushed before finish reading data file
3. Not seen of BTree index for now.

**Comment by linhong-intel** [comment]
@LuciferYang

**Comment by LuciferYang** [comment]
After analysis and exclusion with @linhong-intel , the reason of this issue is that we use fileCatalog.rootPaths.head as outPutPath, and build task temporary path use IndexUtils.getIndexWorkPath method with parameters `inputFile, outputPath, attemptPath, indexFile` , if input parameters as follow:
`/user/spark/test/datawarehouse/test/db/wise/day=20180104/hour=05/minute=05/part-00012
/user/spark/test/datawarehouse/test/db/wise/day=20180104/hour=00/minute=00
/user/spark/test/datawarehouse/test/db/wise/day=20180104/hour=00/minute=00/_temporary/0/_temporary/attempt_20180328141156_0001_m_015249_1
.part-00012.1626b392c09.cmatch_index.index
`
it will not successful replace  `_temporary dir` part to `inputfile` path because outputPath is constant and not contains by inputfile, then index file will write to datapath directly but not _temporary dir, it will Impact of ` spark.speculation= true`.

**Comment by linhong-intel** [comment]
Fixed by #640
