### ISSUE TITLE
ORC fileformat support

### ISSUE THREAD

**Issue by gczsjdy** [Intel-bigdata/OAP#819]
We will track the design & seperated tasks here.

**Comment by LuciferYang** [comment]
Very interested in this feature~

**Comment by gczsjdy** [comment]
@lee-lei will update the design doc here

**Comment by lee-lei** [comment]
I will update the design doc after the internal review. Thanks.

**Comment by lee-lei** [comment]
Currently the ORC support has a series of four PRs as follows. The detailed descriptions are added in the below separate each PRs.
1.      Add the dependent classes by orc from Spark 2.3
https://github.com/Intel-bigdata/OAP/pull/843
2.      Add the four orc record readers. These are specific for Orc support in OAP.
https://github.com/lee-lei/OAP/pull/2
3.      Add the OrcDataFile and corresponding required code changes.
https://github.com/lee-lei/OAP/pull/3
4.      Add the index creation for orc format
https://github.com/lee-lei/OAP/pull/4

Right now the PR1 and PR2 based on PR1 can pass OAP unit tests. The PR3 based on PR1 and PR2 has several failures. The root cause is narrow down and the exact reason is WIP.

**Comment by gczsjdy** [comment]
Thanks @lee-lei , and you can update the design doc here so it's convenient for Baidu developers

**Comment by lee-lei** [comment]
For the past week, the PR3 based on the PR1 and PR2 passed all of OAP unit tests. The PR4 based on the PR1, PR2, and PR3 passed all of OAP unit tests except one failure. The root cause analysis and fix is ongoing.

The design doc will be uploaded tomorrow.

**Comment by lee-lei** [comment]
The design doc will be uploaded soon. Last week I found that it seems that the format is changed a lot after directly copying from my local machine to google docs. Need to take some time to reorganize it. Thanks.

**Comment by lee-lei** [comment]
The design doc link is here: https://docs.google.com/document/d/1XMFPUiZfcMP2glxl2hOZHerEFbn1PnSKhFLWlza6fPo/edit#

**Comment by LuciferYang** [comment]
already support by lee-lei
