### ISSUE TITLE
DataCache Profiling

### ISSUE THREAD

**Issue by songzhan01** [Intel-bigdata/OAP#851]
Current problems as follows:

1、The cache information is reported to driver by a fixed heartbeat interval. However, some sql execution time is very short, may be less than heartbeat interval,  and rerun the sql will not hit the cache.

2、Statistical analysis is time consuming,  we need to analyze this process.

3、Executor's GC Time.

4、Memory localization only use a single-copy cache, but there may be multiple cache copies in the cluster.

**Comment by gczsjdy** [comment]
For 
- 1, with the heartbeat interval as 2s, this should handle most cases, tasks shorter than that is not OAP cache's target.
- 2, does it happen only when index size/data size is high?
- 3, more information?
- 4, #852 currently return 2 hosts with max Fibers, too many(>2) of this number may also be a problem, because OAP cache will be placed before HDFS locality hosts.

**Comment by LuciferYang** [comment]
Use reflection get filed from OnHeapColumnVector slow 2~3 times than call accessor method.
